package se.kth.IV1350.controller;

/**
 * Thrown when the product registration process fails. Checked exception.
 * @author jakobgotberg
 */

public class ProductRegistrationException  extends Exception{
	

    /**
     * Creates instance when the controller catches an <code>InventoryException</code>. It will not use the message generated by 
     * the lower level exception to ensure encapsulation.
     * @param msg The String in this case is the item description.
     */
	public ProductRegistrationException(String msg){
		super("Could not register product. The item description \"" + msg + "\" is an invalid item description.");
	}
	

}
